# python_venv_build ansible role
- name: python_venv_build
  src: https://opendev.org/openstack/ansible-role-python_venv_build.git
  version: master
# ansible-config_template action plugin
- name: config_template
  src: https://opendev.org/openstack/ansible-config_template.git
  version: master
